version: "3.0"
services:
  db:
    image: postgres:13-alpine
    ports: [ '5432:5432' ]
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: api
  db_admin:
    image: dpage/pgadmin4:latest 
    ports: ['8080:8080']
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: password