version: "3.0"
services:
  db:
    image: postgres:13-alpine
    ports: ['5432:5432']
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: api
  db_admin:
    image: dpage/pgadmin4:latest
    depends_on: [db]
    ports: ['8080:8080']
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: password
  server:
    build: .
    ports: ['3000:3000']
    depends_on: [db]
    environment:
      PG_HOST: db
      PG_USERNAME: username
      PG_PASSWORD: password
      PG_DATABASE: api